"""initial

Revision ID: cb4c68125d29
Revises: 
Create Date: 2026-03-28 15:59:06.471243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4c68125d29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('is_group', sa.Boolean(), nullable=False, comment='False = 1-to-1 direct message; True = group (future scope)'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='Group name — null for 1-to-1 conversations'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='E.164 format, e.g. +601XXXXXXXX'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Chosen during profile setup'),
    sa.Column('profile_picture_key', sa.String(length=512), nullable=True, comment='S3 object key — never a public URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('contacts',
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='The user who owns this contact entry'),
    sa.Column('contact_id', sa.UUID(), nullable=False, comment='The user being saved as a contact'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='Optional local nickname shown instead of display_name'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_id', name='uq_contact_pair')
    )
    op.create_index(op.f('ix_contacts_contact_id'), 'contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contacts_owner_id'), 'contacts', ['owner_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False, comment='e.g. iPhone 15 Pro, Pixel 8'),
    sa.Column('push_token', sa.String(length=512), nullable=True, comment='APNs token (iOS) or FCM registration token (Android)'),
    sa.Column('platform', sa.Enum('ios', 'android', name='deviceplatform'), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True, comment='E2EE X25519 public key for this device (Base64 encoded)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('messages_metadata',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'voice', 'image', name='messagetype'), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False, comment='E2EE ciphertext — server cannot read this content'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_destruct', sa.Boolean(), nullable=False, comment='Burn-on-read: client deletes from local DB after first open'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_metadata_conversation_id'), 'messages_metadata', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_metadata_sender_id'), 'messages_metadata', ['sender_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=200), nullable=False, comment='bcrypt hash of the refresh token — never stored plaintext'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_messages_metadata_sender_id'), table_name='messages_metadata')
    op.drop_index(op.f('ix_messages_metadata_conversation_id'), table_name='messages_metadata')
    op.drop_table('messages_metadata')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_contacts_owner_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
